# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c399598dc45a87ba7bbfd7764572fad8"
name = "checkout-app"
handle = "checkout-app-785"
application_url = "https://classifieds-mime-unless-fleet.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "firstappremix.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://classifieds-mime-unless-fleet.trycloudflare.com/auth/callback",
  "https://classifieds-mime-unless-fleet.trycloudflare.com/auth/shopify/callback",
  "https://classifieds-mime-unless-fleet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
